### ISSUE TITLE
StrictMode warning 'close' not called

### ISSUE THREAD

**Issue by franciscofranco** [davemorrissey/subsampling-scale-image-view#128]
Using your lib without any weird mumbo jumbo inside a ViewPager. Let me know if you need more info. Thanks.

```javascript
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at dalvik.system.CloseGuard.open(CloseGuard.java:180)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:181)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:953)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:946)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor.<init>(AssetFileDescriptor.java:359)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor$1.createFromParcel(AssetFileDescriptor.java:372)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor$1.createFromParcel(AssetFileDescriptor.java:371)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:695)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:64)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1400)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1376)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-12 03:07:26.099 19066-19074/com.franco.focus E/StrictMode:     at java.lang.Thread.run(Thread.java:818)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at dalvik.system.CloseGuard.open(CloseGuard.java:180)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:181)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:953)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:946)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor.<init>(AssetFileDescriptor.java:359)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor$1.createFromParcel(AssetFileDescriptor.java:372)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor$1.createFromParcel(AssetFileDescriptor.java:371)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:695)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:63)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1558)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1533)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-12 03:07:26.125 19066-19074/com.franco.focus E/StrictMode:     at java.lang.Thread.run(Thread.java:818)
````

**Comment by davemorrissey** [comment]
Should be fixed by that commit ^, although consistently reproducing the problem and then demonstrating it's fixed is difficult.

**Comment by franciscofranco** [comment]
Thanks Dave. Have a good one!
