### ISSUE TITLE
Another inputStream not closed

### ISSUE THREAD

**Issue by franciscofranco** [davemorrissey/subsampling-scale-image-view#131]
Hey Dave. Found another one:

```javascript
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at dalvik.system.CloseGuard.open(CloseGuard.java:180)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:181)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:953)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:946)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor.<init>(AssetFileDescriptor.java:359)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor$1.createFromParcel(AssetFileDescriptor.java:372)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.res.AssetFileDescriptor$1.createFromParcel(AssetFileDescriptor.java:371)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:695)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:64)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1400)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1376)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-13 22:37:36.604 28696-28704/com.franco.focus E/StrictMode:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by franciscofranco** [comment]
Let me know if you need more info, code samples, or the pictures that are triggering the resource leak.
