### ISSUE TITLE
OutOfMemoryError reported by Crashlytics 

### ISSUE THREAD

**Issue by baole** [davemorrissey/subsampling-scale-image-view#138]
I use Crashlytics and received several crash report as below:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 10328076 byte allocation with 9496656 free bytes and 9MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(BitmapRegionDecoder.java)
       at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
       at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:75)
       at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1485)
       at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1459)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

This issue occurs on both low end and high end devices.

**Comment by baole** [comment]
I use subsampling-scale-image-view version 3.4.0

**Comment by baole** [comment]
Hi @davemorrissey, please merge this issue with #68 and close it. I'm sorry for this redundancy

**Comment by davemorrissey** [comment]
Okay, hope the comments on #68 help.
