### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range 

### ISSUE THREAD

**Issue by patrickdw1991** [davemorrissey/subsampling-scale-image-view#153]
```
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:1979)
at android.support.v4.view.bi.c(SourceFile:32)
at android.support.v4.view.be.c(SourceFile:110)
at android.support.v4.view.bc.c(SourceFile:462)
at android.support.v4.view.ViewPager.onInterceptTouchEvent(SourceFile:1916)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1908)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2146)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
at android.app.Activity.dispatchTouchEvent(Activity.java:2523)
at android.support.v7.internal.view.j.dispatchTouchEvent(SourceFile:60)
at android.support.v7.internal.view.j.dispatchTouchEvent(SourceFile:60)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2094)
at android.view.View.dispatchPointerEvent(View.java:7996)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4656)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4475)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4021)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4071)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4040)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4147)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4048)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4204)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4021)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4071)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4040)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4048)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4021)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6604)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6558)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6790)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6752)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6818)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:558)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5322)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
at dalvik.system.NativeStart.main(Native Method)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
at android.support.v7.internal.view.j.dispatchTouchEvent(SourceFile:60)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3694)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3660)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3668)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3640)
```

**Comment by davemorrissey** [comment]
There's no indication in this stack trace that this library was involved in any way, and you haven't provided an explanation or steps to reproduce.
