### ISSUE TITLE
Use in ViewPager

### ISSUE THREAD

**Issue by shingohu** [davemorrissey/subsampling-scale-image-view#159]
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@42bdfb30

**Comment by davemorrissey** [comment]
That's a broken link. I need your code and a stack trace and a description of the problem.

**Comment by shingohu** [comment]
the main code in pageAdapter 
public SparseArray<View> mViews;
 public View instantiateItem(ViewGroup container, int position) {
        View view = mViews.get(position);
        if (view == null) {
            view = newView(position);
            mViews.put(position, view);
            view.setTag(position);
            container.addView(view);
        }

        if (position == index && !isFirst) {
            isFirst = true;
            updateView(position);
        }


        return view;
    }

and in updateView load the image  
I am use Glide to load image 





12-11 19:02:36.555 4259-4259/com.naodong.xgs.dev303 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.naodong.xgs.dev303, PID: 4259
                                                                      java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@42cc11c8
                                                                          at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1093)
                                                                          at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:827)
                                                                          at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:995)
                                                                          at android.view.View.draw(View.java:14768)
                                                                          at android.view.View.getDisplayList(View.java:13615)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.View.draw(View.java:14470)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                          at android.view.View.getDisplayList(View.java:13607)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.View.draw(View.java:14470)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                          at android.view.View.draw(View.java:14779)
                                                                          at android.support.v4.view.ViewPager.draw(ViewPager.java:2259)
                                                                          at android.view.View.getDisplayList(View.java:13615)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.View.draw(View.java:14470)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                          at android.view.View.draw(View.java:14779)
                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:534)
                                                                          at android.view.View.getDisplayList(View.java:13615)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.View.draw(View.java:14470)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                          at android.view.View.getDisplayList(View.java:13607)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.View.draw(View.java:14470)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                          at android.view.View.getDisplayList(View.java:13607)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.View.draw(View.java:14470)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3268)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3077)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2418)
                                                                          at android.view.View.draw(View.java:14779)
                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:534)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2398)
                                                                          at android.view.View.getDisplayList(View.java:13615)
                                                                          at android.view.View.getDisplayList(View.java:13662)
                                                                          at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1663)
                                                                          at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1538)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2775)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2637)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2253)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1210)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:610)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:578)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:793)
                                                                          at android.os.Handler.handleCallback(Handler.java:808)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
                                                                          at dalvik.system.NativeStart.main(Native Method)
12-11 19:02:36.664 892-5642/system_process E/AEE/LIBAEE: shell: cant create socket with aed: Connection refused
12-11 19:02:45.591 994-994/com.android.systemui E/StatusBar.BatteryController: BatteryController receive ACTION_BATTERY_CHANGED; Battery level = 87; Battery scale = 100
12-11 19:02:55.595 994-994/com.android.systemui E/StatusBar.BatteryController: BatteryController receive ACTION_BATTERY_CHANGED; Battery level = 87; Battery scale = 100

**Comment by davemorrissey** [comment]
If Glide is caching bitmaps, you need to use the `ImageSource.cachedBitmap` static initialiser.
