### ISSUE TITLE
crash when screen was unlocked (onpause and onresume were called)

### ISSUE THREAD

**Issue by gielDevelop** [davemorrissey/subsampling-scale-image-view#161]
12-14 19:06:40.655 18819-18819/com.describeme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
                                                                    at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:777)
                                                                    at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:110)
                                                                    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:995)
                                                                    at android.view.View.draw(View.java:13458)
                                                                    at android.view.View.getDisplayList(View.java:12409)
                                                                    at android.view.View.getDisplayList(View.java:12453)
                                                                    at android.view.View.draw(View.java:13182)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                                    at android.view.View.getDisplayList(View.java:12407)
                                                                    at android.view.View.getDisplayList(View.java:12453)
                                                                    at android.view.View.draw(View.java:13182)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                                    at android.view.View.getDisplayList(View.java:12407)
                                                                    at android.view.View.getDisplayList(View.java:12453)
                                                                    at android.view.View.draw(View.java:13182)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                                    at android.view.View.draw(View.java:13461)
                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                    at android.view.View.getDisplayList(View.java:12409)
                                                                    at android.view.View.getDisplayList(View.java:12453)
                                                                    at android.view.View.draw(View.java:13182)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                                    at android.view.View.getDisplayList(View.java:12407)
                                                                    at android.view.View.getDisplayList(View.java:12453)
                                                                    at android.view.View.draw(View.java:13182)
                                                                    at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
                                                                    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
                                                                    at android.view.View.draw(View.java:13461)
                                                                    at android.widget.FrameLayout.draw(FrameLayout.java:467)
                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2470)
                                                                    at android.view.View.getDisplayList(View.java:12409)
                                                                    at android.view.View.getDisplayList(View.java:12453)
                                                                    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1168)
                                                                    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2149)
                                                                    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2021)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1832)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                    at android.os.Handler.handleCallback(Handler.java:615)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:4931)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:511)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by davemorrissey** [comment]
The sample app doesn't do this, so please provide steps to reproduce, include your code and let me know if you're using a custom image loader.

**Comment by vavan4567** [comment]
Hi, got the same issue. I would be very pleased if you help me fix it. Thanks

**Comment by donpwilson** [comment]
My solution to this issue was as follows:
In the Glide load of the full image do NOT use thumbnail option. Instead, use Glide to load each of the thumbnail and full image into separate SimpleTarget<Bitmap>s. Initialise a boolean flag for "full image loaded" to false. Then, in onResourceReady for the thumbnail check this flag and, if false, set imageView.setImage(...bitmap...). In onResourceReady for the full image set the flag to true and set imageView.setImage(...bitmap...).
This avoids the issue of Glide recycling the thumbnail bitmap (because the full image is ready) but before subsampling-scale-image_view has loaded it.
