### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by xufan** [davemorrissey/subsampling-scale-image-view#162]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24000012 byte allocation with 4194208 free bytes and 19MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
	at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:194)
	at com.android.ui.custom.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:79)
	at com.android.ui.custom.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1575)
	at la.juju.android.ui.custom.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1549)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.OutOfMemoryError: Failed to allocate a 24000012 byte allocation with 4194208 free bytes and 19MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
	at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:194)
	at com.android.ui.custom.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:79)
	at com.android.ui.custom.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1575)
	at com.android.ui.custom.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1549)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

I take all advise in https://github.com/davemorrissey/subsampling-scale-image-view/issues/68
But according to crash report all just happened with Android version 5.0 above.

**Comment by davemorrissey** [comment]
You're using your own copy of the library but haven't provided the code, said which version it's based on, or given the code you're using to configure it.

**Comment by xufan** [comment]
version based on 3.4.1
I'm useing ```Fresco``` to load the image so i change ```SubsamplingScaleImageView``` a little bit.

oom happened in line 97 is ```  Bitmap bitmap = decoder.decodeRegion(sRect, options);```
```
@Override
    public Bitmap decodeRegion(Rect sRect, int sampleSize) {
        synchronized (decoderLock) {
            BitmapFactory.Options options = new BitmapFactory.Options();
            options.inSampleSize = sampleSize;
            options.inPreferredConfig = Config.RGB_565;
            Bitmap bitmap = decoder.decodeRegion(sRect, options);
            if (bitmap == null) {
                throw new RuntimeException("Skia image decoder returned null bitmap - image format may not be supported");
            }
            return bitmap;
        }
    }
```
code in ```SubsamplingScaleImageView``` to show Image:
```
        ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url)).build();
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        DataSource<CloseableReference<PooledByteBuffer>> dataSource = imagePipeline.fetchEncodedImage(imageRequest, this);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(mDraweeHolder.getController())
                .setImageRequest(imageRequest)
                .build();
        DataSubscriber<CloseableReference<PooledByteBuffer>> dataSubscriber =
                new BaseDataSubscriber<CloseableReference<PooledByteBuffer>>() {
                    @Override
                    protected void onNewResultImpl(
                            DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                        if (!dataSource.isFinished()) {
                            return;
                        }
                        CloseableReference<PooledByteBuffer> bytes = dataSource.getResult();
                        if (bytes != null) {
                            PooledByteBuffer pooledByteBuffer = bytes.get();
                            PooledByteBufferInputStream sourceIs = new PooledByteBufferInputStream(pooledByteBuffer);
                            try {
                                BufferedInputStream bis = new BufferedInputStream(sourceIs);
                                String filename = String.valueOf(url.hashCode());
                                FileCache fileCache = new FileCache(getContext());
                                final File f = new File(fileCache.getCacheDir(), filename);
                                OutputStream os = null;
                                try {
                                    f.createNewFile();
                                    os = new FileOutputStream(f);
                                    byte[] buffer = new byte[1024];
                                    int bufferLength;
                                    while ((bufferLength = bis.read(buffer)) != -1) {
                                        os.write(buffer, 0, bufferLength);
                                    }
                                } catch (IOException e) {
                                    e.printStackTrace();
                                } finally {
                                    if (os != null) {
                                        try {
                                            os.close();
                                        } catch (IOException e) {
                                            e.printStackTrace();
                                        }
                                    }
                                    if (bis != null) {
                                        try {
                                            bis.close();
                                        } catch (IOException e) {
                                            e.printStackTrace();
                                        }
                                    }
                                }
                                final int wh[] = ImageHelp.getWithHeight(f.getAbsolutePath());
                                new Handler(Looper.getMainLooper()).post(new Runnable() {
                                    @Override
                                    public void run() {
                                        setImage(ImageSource.uri(f.getAbsolutePath()));
                                        setMaxScale(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
                                        int width = getWidth();
                                        int height = getHeight();
                                        if (width == 0 || height == 0) {
                                            width = DisplayUtil.getScreenWidth();
                                            height = DisplayUtil.getScreenHeight();
                                        }
                                        if ((wh[1]> height) && wh[1] / wh[0] > height / width) {
                                            PointF center = new PointF(getSWidth() / 2, 0);
                                            float targetScale = Math.max(width / (float) wh[0], height / (float)wh[1]);
                                            setScaleAndCenter(targetScale, center);
                                        }
                                    }
                                });
                            } catch (Exception e) {
                                e.printStackTrace();
                            } finally {
                                dataSource.close();
                                CloseableReference.closeSafely(bytes);
                            }
                        }
                    }

                    @Override
                    protected void onFailureImpl(
                            DataSource<CloseableReference<PooledByteBuffer>> dataSource) {
                    }
                };
        dataSource.subscribe(dataSubscriber, CallerThreadExecutor.getInstance());
        mDraweeHolder.setController(controller);
```

**Comment by davemorrissey** [comment]
I'm sorry, I can't provide support for customised versions of the library or use in conjunction with third party libraries - either the changes or the third party library may be the cause of the crash. If you can reproduce an out of memory error with the same image stored as an asset or local file and an unmodified copy of this library, that can be raised as a bug.

**Comment by Piasy** [comment]
I've just created a big image viewer supporting pan and zoom, with very little memory usage and full featured image loading choices. Powered by Subsampling Scale Image View, Fresco, Glide, and Picasso https://github.com/Piasy/BigImageViewer , hope it helps :)
