### ISSUE TITLE
Out of memory exception when load from raw folder

### ISSUE THREAD

**Issue by vajiralasantha** [davemorrissey/subsampling-scale-image-view#169]
Hi, First of all thank you for creating this lib. It is really useful.

However I'm developing an app using your lib and it loads some high res (2560x2560) images from res/raw folder. When I do that, it gives me following exception.
```
Out of memory on a 52428812-byte allocation.
"AsyncTask #3" prio=5 tid=14 RUNNABLE
| group="main" sCount=0 dsCount=0 obj=0xa92c45d8 self=0xb96c0aa0
| sysTid=16272 nice=10 sched=3/0 cgrp=[fopen-error:2] handle=-1184750400
| schedstat=( 149667464 30603773 80 ) utm=14 stm=0 core=0
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:500)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:353)
at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:376)
at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:56)
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1558)
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1533)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 16272 (AsyncTask #3)
```

I can successfully load them from drawable-nodpi. Is there a way to load them from raw folder without this memory issue?
I use ```ImageSource.resource(imageId)``` to fetch image.

Thanks.

**Comment by davemorrissey** [comment]
It looks like your code is forcing the view to load the whole image as one bitmap, I'm guessing it isn't possible to load it from raw using tiling. I'd suggest moving the image to assets or drawable-nodpi.

**Comment by vajiralasantha** [comment]
Hi, I got it working using following code.

```BitmapFactory.Options bitmapOptions =  new BitmapFactory.Options();```
```bitmapOptions.inDither = true;```
```bitmapOptions.inPreferredConfig = Bitmap.Config.RGB_565;```
```bitmapOptions.inScaled = false;```
```Bitmap bitmapImage = BitmapFactory.decodeResource(getResources(), imageId, bitmapOptions);```
```return ImageSource.bitmap(bitmapImage);```

I'm sure this is not the best way to do this. But it works well. Thanks.
