### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by themesbunch** [davemorrissey/subsampling-scale-image-view#202]
First of all, thank you very much for writing this library.

I' m using this library to display Transit maps in my application. I'm having lots of crashes in production app.

This is what i got from play store.

java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 111402012 byte allocation with 16777120 free bytes and 96MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:726)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:547)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:575)
	at com.davemorrissey.labs.subscaleview.a.e.a(Unknown Source)
	at com.davemorrissey.labs.subscaleview.i.a(Unknown Source)
	at com.davemorrissey.labs.subscaleview.i.doInBackground(Unknown Source)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

App is loading 1.2 MB image (3000px x 2500px). But the problem is it never releases the memory, even if you close the activity.

**Code**

On Create:
            imageView = (SubsamplingScaleImageView) findViewById(R.id.img);
            imageView.setImage(ImageSource.resource(R.drawable.subway));

On Destroy:
 if (imageView != null) {
                imageView.destroyDrawingCache();
                imageView.recycle();
                imageView.setImage(null);

                imageView = null;
                System.gc();
                Runtime.getRuntime().gc();
            }

If you can suggest me something?. Thanks

**Comment by davemorrissey** [comment]
Did you put this image in drawable-nodpi? I strongly recommend putting images in assets instead of resources because Android will scale drawables according to screen density, which isn't relevant for an image you're going to zoom into. The memory allocation of 106Mb for this image suggests Android is scaling it.

**Comment by themesbunch** [comment]
Ohh man. Thanks. It worked. I didn't know this. Really appreciated.
