### ISSUE TITLE
Crash happened at:com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1010)

### ISSUE THREAD

**Issue by boybeak** [davemorrissey/subsampling-scale-image-view#213]
`Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2abda1a1
                                                                java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@2abda1a1
                                                                    at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
                                                                    at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:589)
                                                                    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1010)
                                                                    at android.view.View.draw(View.java:16209)`

I use this lib like below:
`Glide.with(this).load(mGalleryItem.getStanderImageUrl()).asBitmap().into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                mThumbBmp = resource;
                mIv.setImage(ImageSource.bitmap(resource));
            }
        });`

when I finish this Activity and turn in this Activity again and again whth loading the same picture,crash happened.

This happened on Samsung Note 4,android 5.0.1

**Comment by davemorrissey** [comment]
Use `ImageSource.cachedBitmap` instead of `ImageSource.bitmap`

**Comment by gurnisht** [comment]
Happened to me with ImageSource.cachedBitmap

**Comment by ankitbatra11** [comment]
I see it with `ImageSource.cachedBitmap` as well. @gurnisht Were you able to find a solution to your problem?
