### ISSUE TITLE
OOM exception

### ISSUE THREAD

**Issue by locomain** [davemorrissey/subsampling-scale-image-view#214]
when loading a (large) image from a path this exception is thrown.

Failed to load bitmap - OutOfMemoryError
                                                                                 java.lang.OutOfMemoryError: Failed to allocate a 24385548 byte allocation with 1477232 free bytes and 1442KB until OOM
                                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                                     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
                                                                                     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
                                                                                     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
                                                                                     at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:61)
                                                                                     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1576)
                                                                                     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1551)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

the image then actually loads but when backpressing the app force closes.

it happends when i try to call: mImageView.setImage(ImageSource.uri(mImage.getPath()));

my xml is:
    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

**Comment by davemorrissey** [comment]
Please check through closed OOME issues, there may be a solution in one of them.

One possibility is BitmapFactory can decode the image but BitmapRegionDecoder cannot read its bounds correctly. Please attach the image.

**Comment by locomain** [comment]
i already did but sadly i could not find a solution in one of them.
the error accures on more then one image and its actually happening frequently.

the BitmapRegionDecor also throws a error here and there but this is actually not really noticable.
also i know this doesnt belong in this issue but before posting a new one i would like to ask if there is a reason for a different imagesizes between the subsamplingimageview and the android imageview?

thank you for your time

**Comment by davemorrissey** [comment]
What do you mean by different image sizes?

**Comment by locomain** [comment]
![screenshot_20160514-215528](https://cloud.githubusercontent.com/assets/1795993/15270541/a0e3eb56-1a23-11e6-8cc5-42904713e5c6.png)

**Comment by davemorrissey** [comment]
That's just the default behaviour. You can change it if you want, see the wiki. The view wasn't really intended for displaying small images.

**Comment by locomain** [comment]
o oke thank you
