### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by chenlulujing** [davemorrissey/subsampling-scale-image-view#238]
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 15980556 byte allocation with 4089500 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:433)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:61)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1558)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1533)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by davemorrissey** [comment]
Please read through closed issues before raising a new one. If you're going to raise a new issue, code, steps to reproduce, details of the device, and the image you have a problem with are required.
