### ISSUE TITLE
InstantiationException: Failed to initialise bitmap decoder

### ISSUE THREAD

**Issue by atomd** [davemorrissey/subsampling-scale-image-view#248]
I got the InstantiationException:

E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
                                                                          java.lang.InstantiationException: java.lang.Class<com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder> has no zero argument constructor
                                                                              at java.lang.Class.newInstance(Native Method)
                                                                              at com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory.make(CompatDecoderFactory.java:18)
                                                                              at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1414)
                                                                              at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1391)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by davemorrissey** [comment]
Please post your code.

**Comment by atomd** [comment]
Sorry to reply so late，I try to load image from `content://media/external/images/media/9250`，And then encountered this error.

**Comment by davemorrissey** [comment]
Please post your code, this is not enough information.

**Comment by RohanShinde03** [comment]
Same issue while loading image from url ...

Tried with  

1. iv_scaleImage_thumbnail.setImage(banner_path!=null ?  ImageSource.uri(Uri.fromFile(new File(banner_path))) : ImageSource.resource(R.drawable.gif_animated_gallery));

Logcat :-

2019-09-07 12:54:10.757 24781-24845/com.myapp.app E/ScaleImageView: Failed to initialise bitmap decoder
    java.io.FileNotFoundException: /http:/192.168.1.18:8000/my_school/public/database_images/event_banner/9/1567075328.png (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:158)
        at com.myapp.app.util.scaleImage.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:101)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1544)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1519)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)




2.  iv_scaleImage_thumbnail.setImage(banner_path!=null ?  ImageSource.uri(banner_path) : ImageSource.resource(R.drawable.gif_animated_gallery));

Logcat :-

2019-09-07 13:05:45.938 29383-29569/com.myapp.app E/ScaleImageView: Failed to initialise bitmap decoder
    java.io.FileNotFoundException: No content provider: http://192.168.1.18:8000/my_school/public/database_images/event_banner/9/1567075328.png
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1461)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1312)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1032)
        at com.myapp.app.util.scaleImage.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:106)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1544)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1519)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Tried with  

1. iv_scaleImage_thumbnail.setImage(banner_path!=null ?  ImageSource.uri(Uri.fromFile(new File(banner_path))) : ImageSource.resource(R.drawable.gif_animated_gallery));

Logcat :-

2019-09-07 12:54:10.757 24781-24845/com.myapp.app E/ScaleImageView: Failed to initialise bitmap decoder
    java.io.FileNotFoundException: /http:/192.168.1.18:8000/my_school/public/database_images/event_banner/9/1567075328.png (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:158)
        at com.myapp.app.util.scaleImage.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:101)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1544)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1519)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)




2.  iv_scaleImage_thumbnail.setImage(banner_path!=null ?  ImageSource.uri(banner_path) : ImageSource.resource(R.drawable.gif_animated_gallery));

Logcat :-

2019-09-07 13:05:45.938 29383-29569/com.myapp.app E/ScaleImageView: Failed to initialise bitmap decoder
    java.io.FileNotFoundException: No content provider: http://192.168.1.18:8000/my_school/public/database_images/event_banner/9/1567075328.png
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1461)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1312)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1032)
        at com.myapp.app.util.scaleImage.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:106)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1544)
        at com.myapp.app.util.scaleImage.ScaleImageView$TilesInitTask.doInBackground(ScaleImageView.java:1519)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by arnaudlvq** [comment]
please don't forget to initialise 👍 

        final Picasso picasso = Picasso.with(plan.getContext());
        image.setBitmapDecoderFactory(new DecoderFactory<ImageDecoder>() {
            public ImageDecoder make() throws InstantiationException {
                return new PicassoDecoder("IMAGE_URL", picasso);
            }
        });
        image.setRegionDecoderFactory(new DecoderFactory<ImageRegionDecoder>() {
            @Override
            public ImageRegionDecoder make() throws InstantiationException {
                return new PicassoRegionDecoder(new OkHttpClient());
            }
        });
