### ISSUE TITLE
Set url to imageView = (SubsamplingScaleImageView) findViewById(R.id.image);

### ISSUE THREAD

**Issue by santafebound** [davemorrissey/subsampling-scale-image-view#254]
I have a method where a Url is queried from my database and sent as an extra before opening the activity where you can zoom, pan, etc.

```java
topLevelMessageImage.setOnClickListener(v - > {

    ParseQuery < ParseObject > imageQuery = new ParseQuery < > (ParseConstants.CLASS_YEET);
    imageQuery.whereEqualTo(ParseConstants.KEY_OBJECT_ID, topLevelCommentObject.getObjectId());
    imageQuery.findInBackground((user, e2) - > {
        if (e2 == null)
            for (ParseObject userObject: user) {

                if (userObject.getParseFile("image") != null) {
                    String imageURL = userObject.getParseFile("image").getUrl();
                    Log.w(getClass().toString(), imageURL);

                    // Asynchronously display the message image downloaded from Parse
                    if (imageURL != null) {

                        Intent intent = new Intent(getApplicationContext(), MediaPreviewActivity.class);
                        intent.putExtra("imageUrl", imageURL);
                        this.startActivity(intent);

                    }

                }
            }
    });
});
```

When the activity starts, I get the following **exception**:

```
java.io.FileNotFoundException: No content provider: https://parsefiles.back4app.com/GDprTC66bNMp3mXWNvWJbZhWwjedoucvp6NlNKVl/03a8e1618392395811c9830333c0443f_6cf1e0ef-47af-4ddc-88cc-196debd77a9a.jpeg
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1090)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
```

I suppose I can't just feed the SubsamplingScaleImageView a Url? What should I do instead?

```java
    private void locateImageView() {

            Bundle bundle = getIntent().getExtras();
            if (bundle != null) {
                if (bundle.getString("imageUrl") != null) {
                    String imageUrl = bundle.getString("imageUrl");
                    Log.w(getClass().toString(), imageUrl);

                    imageView = (SubsamplingScaleImageView) findViewById(R.id.image);

                    URL url = new URL(imageUrl);
                    URI uri = url.toURI();

                    imageView.setImage(ImageSource.uri(String.valueOf(uri)));

                    /*Picasso.with(getApplicationContext())
                            .load(imageUrl)
                            .placeholder(R.color.placeholderblue)
                            .memoryPolicy(MemoryPolicy.NO_CACHE).into(((SubsamplingScaleImageView) findViewById(R.id.image)));*/
                }
            }
```

**Comment by santafebound** [comment]
I actually solved this by creating a Bitmap from the provided URL string extra.

```java
private void locateImageView() throws URISyntaxException, IOException {
        Bundle bundle = getIntent().getExtras();
        if (bundle != null) {
            if (bundle.getString("imageUrl") != null) {
                String imageUrl = bundle.getString("imageUrl");
                Log.w(getClass().toString(), imageUrl);

                imageView = (SubsamplingScaleImageView) findViewById(R.id.image);

                URL newUrl = new URL(imageUrl);

                try {
                    URL url = new URL(imageUrl);
                    HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                    connection.setDoInput(true);
                    connection.connect();
                    InputStream input = connection.getInputStream();
                    Bitmap myBitmap = BitmapFactory.decodeStream(input);

                    imageView.setImage(ImageSource.bitmap(myBitmap));

                } catch (IOException e) {
                    // Log exception
                    Log.w(getClass().toString(), e);
                }

            }
        }
    }
```

**Comment by davemorrissey** [comment]
You can't use an HTTP URL because that doesn't support the random access needed to read tiles from the image. You can download the image and save it locally, or browse through past issues, the wiki and StackOverflow answers to find out how to set up Picasso.

**Comment by santafebound** [comment]
What do you mean exactly by I can't use HTTP URL? What features do I lose? It seems to work for me with the code I provided in my second best.

**Comment by davemorrissey** [comment]
You lose the support for images that are too large to fit in memory when decoded. If you're using a large image, some phones may crash with the code in your second post.
