### ISSUE TITLE
Setting image from Uri ImageSource throws InstantiationException

### ISSUE THREAD

**Issue by rmunk** [davemorrissey/subsampling-scale-image-view#279]
I am trying to load image taken with the camera into `SubsamplingScaleImageView` but it fails and I get caught exception shown in the Logcat. It works if I make the bitmap from the image myself using `BitmapFactory` and use `ImageSource.bitmap()` as the source.
I have checked the image file and it is present on the phone and can be opened without problems.
Here is the code (setting dimensions makes no difference):
```
final ImageSource imageSource = ImageSource.uri(photoFile.getAbsolutePath())
        .dimensions(viewProfilePicture.getWidth(), viewProfilePicture.getHeight())
        .tilingDisabled();
viewProfilePicture.setImage(imageSource);
```
And this is the stack trace from the logs:
```
E/SubsamplingScaleImageView: Failed to load bitmap
      java.lang.InstantiationException: class com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder has no zero argument constructor
      at java.lang.Class.newInstance(Class.java:1681)
      at com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory.make(CompatDecoderFactory.java:18)
      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1688)
      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1662)
      at android.os.AsyncTask$2.call(AsyncTask.java:292)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:818)
      Caused by: java.lang.NoSuchMethodException: <init> []
      at java.lang.Class.getConstructor(Class.java:531)
      at java.lang.Class.getDeclaredConstructor(Class.java:510)
      at java.lang.Class.newInstance(Class.java:1679)
      at com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory.make(CompatDecoderFactory.java:18) 
      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1688) 
      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1662) 
      at android.os.AsyncTask$2.call(AsyncTask.java:292) 
      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
      at java.lang.Thread.run(Thread.java:818) 
```

**Comment by davemorrissey** [comment]
Have you modified the code in any way? Which version are you using?

**Comment by rmunk** [comment]
I am using the latest version 3.6.0 without any modifications. 
`viewProfilePicture` is of a `ProfilePictureView` class extending `SubsamplingScaleImageView` but I only override `onDraw` in it to draw some gridlines over the image.

**Comment by rmunk** [comment]
Any news here? Can I do anything to help you debug this issue?

**Comment by rmunk** [comment]
Ok, I figured out it is a minification issue. If you set `minifyEnabled true` in build.gradle it removes empty constructor from `SkiaImageDecoder` and `SkiaImageRegionDecoder`.

I solved it by adding following line to proguard-rules.pro:
```
-keep class com.davemorrissey.labs.subscaleview.** { *; }
```

It would be good to document this in the setup page in the wiki.

**Comment by davemorrissey** [comment]
Have you used gradle to include the library or included the code manually? I'm surprised this hasn't been raised before - I would have expected it to be a common problem if it occurs when using gradle.

**Comment by rmunk** [comment]
I used gradle: `compile 'com.davemorrissey.labs:subsampling-scale-image-view:3.6.0'`

But I also use the _Android plugin shrinker_ in debug builds to avoid the 64K method limit:
```
        debug {
            minifyEnabled true
            useProguard false
            proguardFile 'proguard-debug.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            useProguard true
            signingConfig signingConfigs.release
            proguardFile 'proguard-rules.pro'
        }
```
It looks like it removes zero argument constructor from `SkiaImageDecoder` and `SkiaImageRegionDecoder` while _Proguard_ which is used in the release build keeps it.

Anyway, I hope this helps someone if they stumble upon this issue.

**Comment by davemorrissey** [comment]
Okay, thanks. I may be able to include proguard rules in the .aar file to preserve these constructors.

**Comment by davemorrissey** [comment]
The next release will include proguard config to preserve the default constructors.
