### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3a1f4260

### ISSUE THREAD

**Issue by lomoya90** [davemorrissey/subsampling-scale-image-view#280]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3a1f4260
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:593)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1127)

**Comment by davemorrissey** [comment]
Duplicate of #213. Please search closed issues before raising a new one.

**Comment by lomoya90** [comment]
Thank you! I see it, but why?
