### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jalonray** [davemorrissey/subsampling-scale-image-view#324]
I got this crash:
java.lang.UnsatisfiedLinkError: android.media.ExifInterface
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.a(SubsamplingScaleImageView.java:1805)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.a(SubsamplingScaleImageView.java:81)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$j.a(SubsamplingScaleImageView.java:1518)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$j.doInBackground(SubsamplingScaleImageView.java:1490)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by davemorrissey** [comment]
I think this is a build error, and not directly related to this library. Have you tried it on other devices? Does this happen with production builds only or debug too? Have you searched for e.g. `java.lang.UnsatisfiedLinkError android` to find causes of this error?
