### ISSUE TITLE
NPE on onTouchEvent for PointF.x

### ISSUE THREAD

**Issue by scastro** [davemorrissey/subsampling-scale-image-view#336]
Hi,

I check the issues for something similar but couldn't found an issue similar to this one.
I'm getting a lot of NPE on the onTouchEvent and I don't really know how to even reproduce it or why is happening. So, maybe someone experience this or know some way to at least detect the issue. Here is the crash log I get in every single crash report for this issue.

`Exception dispatching input event.
Exception in MessageQueue callback: handleReceiveCallback
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
	at android.graphics.PointF.set(PointF.java:54)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEvent(SubsamplingScaleImageView.java:656)
	at android.view.View.dispatchTouchEvent(View.java:10779)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:607)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:569)
	at android.view.View.dispatchPointerEvent(View.java:11008)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
`

I'm using version 3.6.0

Thanks in advance

**Comment by davemorrissey** [comment]
When you say "a lot", can you explain - is that lots of times across thousands of installs, lots of times every time you use the view e.g. when panning, lots of times but only once each time the view loads? This is a strange one, it looks like a possible multithreading race condition, but even then it's hard to see how `vTranslate` can be null on that line. Can you provide more details of your setup?

**Comment by m4rkus** [comment]
i also get this when doing fast pans

**Comment by steelbytes** [comment]
sadly me to with v3.10.0

I don't  have a repro method as I'm seeing a few of these in play console crash logs

**Comment by victorfan336** [comment]
I had the same problem with v3.10.0 . Why close the issue without solving it ？ Any ideas to solve this crash ? Thanks. @davemorrissey

**Comment by victorfan336** [comment]
I checked our crash log statistics. This crash happened recently. Recently, we have upgraded the Android version, some plug-in versions, and some library versions before this crash occurred, but I'm not sure about the specifics. Not because of our version upgrade. After all, I didn’t have this crash problem when I started using this library.
Any ideas ?thanks. v3.10.0
