### ISSUE TITLE
get a error

### ISSUE THREAD

**Issue by ananas-xxj** [davemorrissey/subsampling-scale-image-view#337]
java.io.IOException: Image failed to decode using JPEG decoder
                                                                                         at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
                                                                                         at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
                                                                                         at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
                                                                                         at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:62)
                                                                                         at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1515)
                                                                                         at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1490)
                                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by davemorrissey** [comment]
There are many closed issues with errors like this. Please search through them for possible solutions before raising a new issue.
