### ISSUE TITLE
Got an internal exception when loading a PNG file from local file storage

### ISSUE THREAD

**Issue by rayworks** [davemorrissey/subsampling-scale-image-view#345]
```
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
        java.io.IOException: Invalid marker: 89
            at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
            at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
            at android.media.ExifInterface.<init>(ExifInterface.java:1112)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1805)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.access$5200(SubsamplingScaleImageView.java:81)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1689)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1662)
            at android.os.AsyncTask$2.call(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            at java.lang.Thread.run(Thread.java:762)
```

It seems there is a bug in ```ExifInterface```.
A related linkage can also be found [here](https://github.com/Yalantis/uCrop/issues/182).

**Comment by davemorrissey** [comment]
This is logged as a warning only and you can ignore it. EXIF orientation is unsupported for PNG images but the view doesn't know whether it's dealing with a PNG or JPG so just attempts it for every image. If you know for a fact you're loading a PNG image, don't enable EXIF orientation and this warning won't be logged.
