### ISSUE TITLE
Hello, I'm using glide to load the image and show it in the viewpager, and I can't zoom,

### ISSUE THREAD

**Issue by fanpengfei1993** [davemorrissey/subsampling-scale-image-view#375]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Insufficient information provided. Please complete the template.

**Comment by fanpengfei1993** [comment]
SubsamplingScaleImageView.setDebug(true);  No information was displayed,And There is no problem loading local images

**Comment by davemorrissey** [comment]
Please complete the template, I need more information.

**Comment by fanpengfei1993** [comment]
/SubsamplingScaleImageView: Failed to initialise bitmap decoder
                                                                                   java.io.FileNotFoundException: No content provider: http://192.168.50.123:8080/public/0B80125DF8E.jpg
                                                                                       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1142)
                                                                                       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:993)
                                                                                       at android.content.ContentResolver.openInputStream(ContentResolver.java:713)
                                                                                       at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:67)
                                                                                       at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1515)
                                                                                       at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1490)
                                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:316)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                       at java.lang.Thread.run(Thread.java:776)

**Comment by davemorrissey** [comment]
Please read the wiki and follow setup instructions before raising bugs. Web URLs are not supported. Download the image first.
