### ISSUE TITLE
 java.io.IOException: Image format not supported   ..url http://interfacelift.com/wallpaper/Dd96106d/04139_thefreshairofsaentismountain_4096x2160.jpg

### ISSUE THREAD

**Issue by tqlmorepassion** [davemorrissey/subsampling-scale-image-view#400]
Failed to initialise bitmap decoder
                                                                                  java.io.IOException: Image format not supported
                                                                                      at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
                                                                                      at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
                                                                                      at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
                                                                                      at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:75)
                                                                                      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1516)
                                                                                      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1491)
                                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                      at java.lang.Thread.run(Thread.java:760)
02-28 13:20:21.852 3836-4002/net.medlinker.medlinker E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
                                                                                  java.io.IOException: Image format not supported
                                                                                      at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
                                                                                      at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
                                                                                      at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
                                                                                      at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:75)
                                                                                      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1516)
                                                                                      at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1491)
                                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                      at java.lang.Thread.run(Thread.java:760)

**Comment by davemorrissey** [comment]
URLs are not supported. When opening issues, please do not delete the issue template.

**Comment by tqlmorepassion** [comment]
![wechatimg682](https://user-images.githubusercontent.com/8497657/36775436-013cd878-1c9d-11e8-842d-670d8b7b50b6.jpeg)
release apk preduce this exception,but debut apk is ok.
url : http://pub-med-casem.imgs.medlinker.net/6B42F908-1D86-488D-8034-8652CA7D77AD?imageMogr2/thumbnail/!80p/interlace/1#MED_IMG_CHECKED

**Comment by tqlmorepassion** [comment]
@davemorrissey

**Comment by davemorrissey** [comment]
Can you complete the standard issue template please?

**Comment by tqlmorepassion** [comment]
@davemorrissey sorry。
