### ISSUE TITLE
Attempt to read from field 'float android.graphics.PointF.x' on a null object reference

### ISSUE THREAD

**Issue by SherlockGougou** [davemorrissey/subsampling-scale-image-view#404]
Hello, I received many such errors, I don’t know what caused it.What should I do? How to solve this problem? Thank you!
```
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference
	at android.graphics.PointF.set(PointF.java:54)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEvent(SubsamplingScaleImageView.java:691)
	at android.view.View.dispatchTouchEvent(View.java:10128)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:437)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1841)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3099)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
	at android.view.View.dispatchPointerEvent(View.java:10359)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5032)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4865)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4385)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4351)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4498)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4359)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4555)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4385)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4351)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4359)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4332)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6947)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6921)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6864)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7128)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:191)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:328)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:6406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
```

**Comment by davemorrissey** [comment]
When opening an issue please can you complete the issue template instead of deleting it? It would provide useful information.

**Comment by davemorrissey** [comment]
Insufficient information provided.
