### ISSUE TITLE
ExifInterface crash (StackOverflowError)

### ISSUE THREAD

**Issue by rubengees** [davemorrissey/subsampling-scale-image-view#427]
I have received a report from an user that a specific image (sorry, can't share) does not load. Upon investigation, I found that this is caused by `ExifInterface` throwing a `StackOverflowError`due to a [bug](https://stackoverflow.com/questions/43246732/calling-exifinterface-in-a-loop-causing-java-lang-stackoverflowerror). Is there a way to either disable `ExifInterface` (I know the orientation of my images) or catch this error (currently only `Exceptions` but no `Errors` are catched) to avoid crashing the entire app?

### Expected behaviour

The app does not crash, even though `ExifInterface` throws an error.

### Actual behaviour

The app does crash with this stacktrace:

```ruby
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.StackOverflowError: stack size 1037KB
        at java.util.HashMap.getNode(HashMap.java:571)
        at java.util.HashMap.get(HashMap.java:556)
        at android.support.media.ExifInterface.readImageFileDirectory(ExifInterface.java:5343)
        at android.support.media.ExifInterface.readImageFileDirectory(ExifInterface.java:5459)
        at android.support.media.ExifInterface.readImageFileDirectory(ExifInterface.java:5459)
        ...
     at android.support.media.ExifInterface.readExifSegment(ExifInterface.java:5241)
        at android.support.media.ExifInterface.getJpegAttributes(ExifInterface.java:4863)
        at android.support.media.ExifInterface.loadAttributes(ExifInterface.java:4209)
        at android.support.media.ExifInterface.<init>(ExifInterface.java:3715)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1860)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.access$5200(SubsamplingScaleImageView.java:72)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1562)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

### Steps to reproduce

- Find an image triggering this behaviour.
- Find a device triggering this behaviour.
- Load the image.

```kt
image.setSource(ImageSource.uri(resource.path)) // resource is an existing java.io.File. 
```

### Affected devices

Reproduced on my `OnePlus 5T` with Android 8.1.

**Comment by rubengees** [comment]
@davemorrissey Friendly ping, anything new on this issue?

**Comment by davemorrissey** [comment]
Closing this now as there haven't been any more reports and without the image it can't be reproduced. The error is almost certainly within Android code.
