### ISSUE TITLE
Crash at refreshRequiredTiles on Oreo while zooming images

### ISSUE THREAD

**Issue by ch4ndu** [davemorrissey/subsampling-scale-image-view#432]
java.lang.ClassCastException: android.os.AsyncTask$3 cannot be cast to java.lang.Comparable
        at java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:356)
        at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:488)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1381)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.execute(SubsamplingScaleImageView.java:1881)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.refreshRequiredTiles(SubsamplingScaleImageView.java:1312)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEventInternal(SubsamplingScaleImageView.java:783)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEvent(SubsamplingScaleImageView.java:695)
        at android.view.View.dispatchTouchEvent(View.java:12520)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2844)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:600)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3384)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:562)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5615)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5410)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4903)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4956)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4922)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5059)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4930)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5116)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4903)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4956)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4922)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4930)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4903)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7654)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7594)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7555)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7765)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7728)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7792)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:652)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by ch4ndu** [comment]
Using MinimumDpi-160 and a custom executor. Everything else is default.
