### ISSUE TITLE
SubsamplingScaleImageView: Failed to initialise bitmap decoder

### ISSUE THREAD

**Issue by qq309213760** [davemorrissey/subsampling-scale-image-view#460]
SubsamplingScaleImageView: Failed to initialise bitmap decoder
    java.io.IOException: Image format not supported
        at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

//img:url:xxxx9fd12d242fe2195d2223b09730f4fec1.jpg

**Comment by wczhang3** [comment]
我也遇到这个问题了，请问解决了吗

**Comment by LY0328** [comment]
+1 我也遇到这个问题了

**Comment by bingocode** [comment]
+1 我也遇到了，最近升级了glide到4.8.0，用glide下载完的本地图片文件用该库加载就出现这个问题了

**Comment by mzhkby** [comment]
有碰到这个问题，有解决方式吗？

**Comment by davemorrissey** [comment]
Issue template deleted and no image provided so I cannot assist. As the message says your image is not supported by Android.
