### ISSUE TITLE
 Failed to initialise bitmap decoder

### ISSUE THREAD

**Issue by WiseDiligent** [davemorrissey/subsampling-scale-image-view#496]
java.io.IOException: Image format not supported
at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:125)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:156)
        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

please look  help me   ，  thank you

**Comment by davemorrissey** [comment]
Your image format is not supported. https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images
