### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by sunzhishuai** [davemorrissey/subsampling-scale-image-view#501]
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@9a6d635 rejected from java.util.concurrent.ThreadPoolExecutor@34b8aca[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 86]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2104)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1413)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:652)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.execute(SubsamplingScaleImageView.java:1881)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.refreshRequiredTiles(SubsamplingScaleImageView.java:1312)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEventInternal(SubsamplingScaleImageView.java:783)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEvent(SubsamplingScaleImageView.java:695)
        at android.view.View.dispatchTouchEvent(View.java:12628)

**Comment by davemorrissey** [comment]
No information given. Please do not delete the issue template.
