### ISSUE TITLE
Crash due to using recycled bitmap

### ISSUE THREAD

**Issue by JohannesPtaszyk** [davemorrissey/subsampling-scale-image-view#522]
I am using this view inside a RecyclerView. Sometimes I get a crash, because the view is using an already recycled bitmap.
To load the view I am using Glide with a custom target.

### Expected behaviour
The view should not crash, when the bitmap was already recycled.

### Actual behaviour
The view is crashing due to accessing an already recycled bitmap.

### Steps to reproduce

Glide code:

```
Glide.with(imageView.context)
        .asBitmap()
        .override(Target.SIZE_ORIGINAL)
        .diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
        .load(newImageUrl)
        .into(object : CustomTarget<Bitmap>() {
            override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                imageView.setImage(ImageSource.bitmap(resource))
            }
            override fun onLoadCleared(placeholder: Drawable?) {
                //Nothing to do here.
            }
        })
```

Image view layout:

```
<com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/ssiv_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:contentDescription="@{image.altText}"/>
```

Stacktrace:

```
2020-09-01 13:43:12.397 x.x.x.x.x.x W/Bitmap: Called getHeight() on a recycle()'d bitmap! This is undefined behavior!
2020-09-01 13:43:12.400 x.x.x.x.x.x A/Bitmap: Error, cannot access an invalid/free'd bitmap here!
2020-09-01 13:43:12.744 x.x.x.x.x.x A/g.x.alph: runtime.cc:655] Runtime aborting...
    runtime.cc:655] All threads:
    runtime.cc:655] DALVIK THREADS (89):
    runtime.cc:655] "main" prio=10 tid=1 Runnable
    runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x71869c28 self=0xe0c84610
    runtime.cc:655]   | sysTid=18282 nice=-10 cgrp=top-app sched=0/0 handle=0xef1e6478
    runtime.cc:655]   | state=R schedstat=( 20683062532 2437457017 23758 ) utm=703 stm=1365 core=1 HZ=100
    runtime.cc:655]   | stack=0xff7fa000-0xff7fc000 stackSize=8192KB
    runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
    runtime.cc:655]   native: #00 pc 00542d7e  /apex/com.android.art/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+110)
    runtime.cc:655]   native: #01 pc 006a0877  /apex/com.android.art/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+1015)
    runtime.cc:655]   native: #02 pc 0069a151  /apex/com.android.art/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+65)
    runtime.cc:655]   native: #03 pc 006c6194  /apex/com.android.art/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+1172)
    runtime.cc:655]   native: #04 pc 006bf246  /apex/com.android.art/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+630)
    runtime.cc:655]   native: #05 pc 006bdf52  /apex/com.android.art/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1842)
    runtime.cc:655]   native: #06 pc 0065225d  /apex/com.android.art/lib/libart.so (art::AbortState::DumpAllThreads(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*) const+445)
    runtime.cc:655]   native: #07 pc 0063982f  /apex/com.android.art/lib/libart.so (art::Runtime::Abort(char const*)+1967)
    runtime.cc:655]   native: #08 pc 00025a23  /apex/com.android.art/lib/libartbase.so (std::__1::__function::__func<void (*)(char const*), std::__1::allocator<void (*)(char const*)>, void (char const*)>::operator()(char const*&&)+35)
    runtime.cc:655]   native: #09 pc 0001588f  /system/lib/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+79)
    runtime.cc:655]   native: #10 pc 00006dbd  /system/lib/liblog.so (__android_log_assert+285)
    runtime.cc:655]   native: #11 pc 001ce837  /system/lib/libhwui.so (android::CanvasJNI::drawBitmapMatrix(_JNIEnv*, _jobject*, long long, long long, long long, long long)+87)
    runtime.cc:655]   at android.graphics.BaseRecordingCanvas.nDrawBitmapMatrix(Native method)
    runtime.cc:655]   at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:78)
    runtime.cc:655]   at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1111)
```
### Affected devices

Happened on multiple devices including Pixel 3 on Android 10 and on Android 11 Beta.

### Affected images

Independent from image

**Comment by JohannesPtaszyk** [comment]
Seems to work! Thank you!
