### ISSUE TITLE
java.lang.OutOfMemoryError on some devices

### ISSUE THREAD

**Issue by dima1422** [davemorrissey/subsampling-scale-image-view#525]
This library crashes on some devices (Samsung Galaxy A7 2016)

```
E/SubsamplingScaleImageView: Failed to load bitmap - OutOfMemoryError
    java.lang.OutOfMemoryError: Failed to allocate a 52005900 byte allocation with 16777216 free bytes and 18MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
        at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:558)
        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:82)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1743)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1717)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```
Image example:

![figure27](https://user-images.githubusercontent.com/29385317/92968806-712f3100-f484-11ea-8b5f-4f833f5f2ad6.jpg)

**Comment by davemorrissey** [comment]
You have deleted the issue template and not provided your source code so I don't know how you're using the view.
