### ISSUE TITLE
Failed to initialise bitmap decoder

### ISSUE THREAD

**Issue by midou221** [davemorrissey/subsampling-scale-image-view#535]
Sometimes when I show a large group of pictures the app showing this error

log:
> 2020-12-09 13:42:46.849 12857-12857/org.app.examplemanga D/PGL: Complete page 161 id: 0 filename: /storage/emulated/0/Android/data/org.app.examplemanga/cache/uil-images/-1210899930#
2020-12-09 13:42:46.850 12857-12857/org.app.examplemanga D/PGL: Started page 162 id: 0 filename: null#
2020-12-09 13:42:47.192 12857-12857/org.app.examplemanga D/PGL: Complete page 162 id: 0 filename: /storage/emulated/0/Android/data/org.app.examplemanga/cache/uil-images/-487932270#
2020-12-09 13:42:47.193 12857-12857/org.app.examplemanga D/PGL: Started page 163 id: 0 filename: null#
2020-12-09 13:42:47.403 12857-13129/org.app.examplemanga E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
    java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.app.examplemanga/cache/uil-images/4291077590 (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
2020-12-09 13:42:47.408 12857-13192/org.app.examplemanga E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.app.examplemanga/cache/uil-images/4291077590 (No such file or directory)
2020-12-09 13:42:47.547 12857-12857/org.app.examplemanga D/PGL: Complete page 163 id: 0 filename: /storage/emulated/0/Android/data/org.app.examplemanga/cache/uil-images/7400769500#
2020-12-09 13:42:47.547 12857-12857/org.app.examplemanga D/PGL: Started page 164 id: 0 filename: null#

xml code:
`<?xml version="1.0" encoding="utf-8"?>
<androidx.core.widget.NestedScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:fillViewport="true"
    app:zoomEnabled="false"
    app:quickScaleEnabled="false"
    app:panEnabled="false"
    android:orientation="vertical"
    app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?android:windowBackground">

            <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
                android:id="@+id/ssiv2"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:orientation="vertical">

                <TextView
                    android:id="@+id/textView_holder2"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center"
                    android:textColorLink="?colorAccent"
                    android:visibility="gone" />

                <org.app.examplemanga.AppCompatProgressBar
                    android:id="@+id/progressBar2"
                    style="?android:attr/progressBarStyleHorizontal"
                    android:layout_width="180dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_marginTop="8dp"
                    android:indeterminate="true" />

            </LinearLayout>

        </FrameLayout>

    </LinearLayout>

</androidx.core.widget.NestedScrollView>`

I want to know the cause of the error and how can i avoid it?!

**Comment by davemorrissey** [comment]
The file you are trying to display does not exist.
