### ISSUE TITLE
Image failed to decode using JPEG decoder error with an image that has an sRGB color profile

### ISSUE THREAD

**Issue by Kranuh** [davemorrissey/subsampling-scale-image-view#539]
First of all, thank you for the library. It's great and really helps us out, it _usually_ works as indented. We use it mostly as a photo gallery, causing it to display all kinds of images. It's pretty rare that we find an image that doesn't work, but we did manage to find one. My first thought was that it probably had an CMYK color profile, but after some investigation I found that it was actually an RGB image. So the bug entry:

### Expected behaviour

The image is displayed

### Actual behaviour

The following exception is thrown:

`    java.io.IOException: Image failed to decode using JPEG decoder
        at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
        at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
        at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:102)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)`

### Steps to reproduce

Use the following image as input for the `SubsamplingScaleImageView`:

### Affected devices

Specifically only affects Android version 6.0

### Affected images

See above

**Additional information:**

Using ImageMagick I've confirmed the following color profile:

`JPEG 1240x869 1240x869+0+0 8-bit sRGB 139260B 0.000u 0:00.000`

This kind of image should be supported right? 8 bits RGB?

**Comment by davemorrissey** [comment]
Image display issues are caused by the Skia library, and unfortunately it's not possible to do anything about this in a 5 year old version of Android.
